version: 2.1
jobs:
  build:  
    docker:
      - image: cronapp/sandbox:2.9.1-SP.2
    steps:
        - run:
            name: Install Dependencies
            command: cordova platform add ios
            