version: 2

jobs:
  ios:
    macos:
      xcode: "13.0.0"
    shell: /bin/bash --login -eo pipefail
    steps:
      - checkout
      - run:
          name: Install node/npm
          command: command -v node || brew install node
      - run:
          name: Install Cordova
          command: npm install -g cordova@9.0.0
      - run:
          name: Add iOS platform
          command: cd Example && cordova platform add ios
      - run:
          name: Install intercom plugin
          command: cd Example && cordova plugin add ../intercom-plugin
      - run:
          name: Build
          command: cd Example && cordova build ios --buildFlag="-UseModernBuildSystem=0"