version: 2.1
jobs:
    docker:
      - image: cronapp/sandbox:2.9.1-SP.2
    steps:
     - checkout 
     - run:
        name: Install Dependencies
        command: echo "Hello my Kombis"


            